### PR TITLE
Add missing "return" in aliased functions.

### PR DESCRIPTION
**Pull request by ADmad**
|    Q        |   A
|------------ | ------
| Bugfix      | yes
| BC Break    | no
| New Feature | no
| RFC         | no

### CODE REVIEW

**Comment by ADmad** [comment]
Anything holding up merging this?

**Comment by Xerkus** [comment]
@ADmad more works needs to be done for those than just merge it.  It is being handled.

**Comment by ADmad** [comment]
@Xerkus Thanks for the update.

**Comment by weierophinney** [comment]
I've reviewed, and these are present from release 1.8.0 on.

What I'll be doing is applying the patch to each release and issuing a patch release (e.g., 1.8.0p1). I've confirmed that Composer handles these properly — i.e., they take precedence over the stable tag they're applied against.

Once I've applied to all releases, I'll apply to master and issue a new bugfix release.

**Comment by ADmad** [comment]
Just for reference CakePHP using `zendframework/zend-diactoros` and I discovered this issue when trying to switch to laminas package. The fixes I have done makes our testsuite happy.

**Comment by weierophinney** [comment]
I've tagged 2.2.2 with the change, and issued the following patch releases:

- 1.8.0p1
- 1.8.1p1
- 1.8.2p1
- 1.8.3p1
- 1.8.4p1
- 1.8.5p1
- 1.8.7p1
- 2.0.0p1
- 2.0.1p1
- 2.0.2p1
- 2.0.3p1
- 2.1.0p1
- 2.1.1p1
- 2.1.2p1
- 2.1.3p1
- 2.1.4p1
- 2.1.5p1
- 2.2.0p1
- 2.2.1p1

**Pull request merged**
