### PR TITLE
Add contributing and support details to the README

### PR DESCRIPTION
**Pull request by settermjd**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This PR copies in (and slightly amends) the relevant information for getting support and contributing to the project to the README, to make it as easy as possible for people to do one or both of these.

### CODE REVIEW

**Comment by settermjd** [comment]
Just took another stab at this, @weierophinney.

**Comment by boesing** [comment]
I remember that we did not wanted to have these files part of every component to avoid maintenance hell when changes have to be applied.

linking to these files in the `.github` repo was suggested in the latest TSC meeting.

I did not diff the files, if there are changes, we might want to adapt these to the `.github` repo instead. 

Just my two cents on this. Either way, thanks for your efforts.

**Comment by weierophinney** [comment]
I've sent a PR to @settermjd to demonstrate, @boesing : settermjd/laminas-diactoros#1

**Comment by boesing** [comment]
ah, nice! one thing we have to keep in mind is that there are some packages which do already link to some files. adding to the end of the readme might duplicate some stuff. but I think this might be somehow detectable using grep 👍🏻

**Pull request closed without merging**
