### PR TITLE
Remove marshalUriFromSapi function

### LINKED ISSUE #149: Drop deprecated function marshalUriFromSapi
`Laminas\Diactoros\marshalUriFromSapi()` was deprecated since 2.11 and should be removed in 3.0.

It is only used in `ServerRequestFactoryTest`

### PR DESCRIPTION
**Pull request by weierophinney**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | yes
| New Feature   | no
| RFC           | no
| QA            | no

### Description

In version 2.11.0, we deprecated the `Laminas\Diactoros\marshalUriFromSapi()` function, and moved its functionality to `UriFactory::createFromSapi()`.

This patch removes it for the v3.0.0 release, and documents the removal in the migration guide.

Fixes #149

### CODE REVIEW

**Comment by weierophinney** [comment]
Fixes #149

**Comment by Xerkus** [comment]
psalm config file also has issue handler for this

**Comment by weierophinney** [comment]
> psalm config file also has issue handler for this

Resolved.

**Review by Xerkus — APPROVED** [review]

**Comment by Xerkus** [comment]
Thank you.

**Review by koka500000 — APPROVED** [review]

**Pull request merged**
