### PR TITLE
Add support for PHP 8.4

### PR DESCRIPTION
**Pull request by ADmad**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by ADmad** [comment]
The blocker for getting the testsuite passing is vimeo/psalm still not supporting PHP 8.4 https://github.com/vimeo/psalm/pull/10928

**Comment by gsteel** [comment]
Conflicting with older versions of amphp should get CI over the line here:
https://github.com/mezzio/mezzio-session-ext/pull/56/files

**Comment by ADmad** [comment]
> Conflicting with older versions of amphp should get CI over the line here

Thanks for the tip, done.

**Review by samsonasik — APPROVED** [review]

**Review by gsteel — APPROVED** [review]
Thanks @ADmad :)

**Review by koka500000 — APPROVED** [review]

**Review by koka500000 — COMMENTED** [review]
[]()

**Review by koka500000 — APPROVED** [review]

**Pull request merged**
